version: '3'
services:
 metaflow-compose:
    image: metaflow
    user: meta:meta
    working_dir: /metaflow
    stdin_open: true
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    tty: true
    command: tail -f /dev/null