version: '3'
services:
 metaflow-compose:
    image: metaflow
    user: meta
    working_dir: /metaflow
    stdin_open: true
    volumes:
      - /etc/group:/etc/group:ro
    tty: true
    command: tail -f /dev/null